spring:
  application:
    name: adohdo
  datasource:
    url: jdbc:h2:file:./var/adohdo.h2
    username: sa
    password: ""
  h2:
    console:
      enabled: false
  jpa:
    show-sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            redirect-uri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - user:email
              - read:user
  task:
    scheduling:
      pool:
        size: 16

adohdo:
  auth:
    token-secret: ${AUTH_TOKEN_SECRET}
    token-expiration-msec: 864000000
